


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${aws.db.username}
    password: ${aws.db.password}
    url: ${aws.db.url}
  output:
    ansi:
      enabled: always
  #  batch:
  #    jdbc:
  #      initialize-schema: always
  #    job:
  #      names: myJob
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

  logging:
    level:
      #      root: info
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace
